# Generated by Django 3.1.5 on 2021-02-19 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Category Title')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft')),
                ('title', models.CharField(default='', max_length=58, unique=True, verbose_name='Post Title')),
                ('description', models.CharField(default='', max_length=120, verbose_name='Post Description')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Post URL Slug')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('featured_image', models.ImageField(upload_to='image/', verbose_name='Featured Image (800x570)')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('author', models.ForeignKey(on_delete=models.SET('author'), to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(on_delete=models.SET('category'), to='blog.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=80)),
                ('email', models.EmailField(default='', max_length=254)),
                ('content', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=True)),
                ('test', models.TextField(default='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_on'],
            },
        ),
    ]
