# Generated by Django 3.1.5 on 2021-01-19 17:39

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Category Title')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('title', models.CharField(default='Post Title', max_length=59, unique=True, verbose_name='Post Title')),
                ('snippet', models.CharField(default='Post Snippet', max_length=120, verbose_name='Post Snippet')),
                ('slug', models.SlugField(max_length=65, unique=True, verbose_name='Post URL Slug')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Post Content')),
                ('featured_image', models.ImageField(upload_to='image/', verbose_name='Featured Image (800x570)')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('author', models.ForeignKey(on_delete=models.SET('deleted user'), to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(on_delete=models.SET(''), to='blog.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_on'],
            },
        ),
    ]
