# Generated by Django 3.1.5 on 2021-01-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=255, verbose_name='Duty')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'ordering': ['certification'],
            },
        ),
        migrations.CreateModel(
            name='ComputerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, verbose_name='Duty')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'ordering': ['skill'],
            },
        ),
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='My Name')),
                ('email', models.EmailField(max_length=255, verbose_name='My Email')),
                ('phone', models.CharField(max_length=255, verbose_name='My Phone Number')),
                ('city_state', models.CharField(max_length=255, verbose_name='My Location')),
                ('linkedin', models.CharField(max_length=255, verbose_name='My LinkedIn')),
                ('github', models.CharField(max_length=255, verbose_name='My Git')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=255, verbose_name='Duty')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'ordering': ['interest'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Company Name')),
                ('position', models.CharField(max_length=255, verbose_name='Position Title')),
                ('city_state', models.CharField(max_length=255, verbose_name='Location')),
                ('start_date', models.DateField(max_length=255, verbose_name='Start Date')),
                ('end_date', models.CharField(max_length=255, verbose_name='End Date')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='PersonalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, verbose_name='Duty')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'ordering': ['skill'],
            },
        ),
        migrations.CreateModel(
            name='JobDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=255, verbose_name='Duty')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='resume.job', verbose_name='Company')),
            ],
            options={
                'ordering': ['company'],
            },
        ),
    ]
