# Generated by Django 3.1.5 on 2021-01-28 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=255, verbose_name='Certification')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Certifications',
                'verbose_name_plural': 'Certifications',
                'ordering': ['certification'],
            },
        ),
        migrations.CreateModel(
            name='ComputerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, verbose_name='Skill')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Computer Skills',
                'verbose_name_plural': 'Computer Skills',
                'ordering': ['skill'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255, verbose_name='School Name')),
                ('degree', models.CharField(max_length=255, verbose_name='Degree Title')),
                ('gpa', models.CharField(max_length=255, verbose_name='GPA')),
                ('city_state', models.CharField(max_length=255, verbose_name='Location')),
                ('start_date', models.DateField(max_length=255, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, max_length=255, null=True, verbose_name='End Date')),
                ('currently_enrolled', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Currently Enrolled Here')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-currently_enrolled'],
            },
        ),
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='My Name')),
                ('email', models.EmailField(max_length=255, verbose_name='My Email')),
                ('phone', models.CharField(max_length=255, verbose_name='My Phone Number')),
                ('city_state', models.CharField(max_length=255, verbose_name='My Location')),
                ('linkedin', models.CharField(max_length=255, verbose_name='My LinkedIn')),
                ('github', models.CharField(max_length=255, verbose_name='My Git')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'General Information',
                'verbose_name_plural': 'General Information',
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=255, verbose_name='Interest')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Interests',
                'verbose_name_plural': 'Interests',
                'ordering': ['interest'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Company Name')),
                ('position', models.CharField(max_length=255, verbose_name='Position Title')),
                ('city_state', models.CharField(max_length=255, verbose_name='Location')),
                ('start_date', models.DateField(max_length=255, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, max_length=255, null=True, verbose_name='End Date')),
                ('currently_employed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Currently Employed Here')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-currently_employed'],
            },
        ),
        migrations.CreateModel(
            name='PersonalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, verbose_name='Skill')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Personal Skills',
                'verbose_name_plural': 'Personal Skills',
                'ordering': ['skill'],
            },
        ),
        migrations.CreateModel(
            name='JobDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=255, verbose_name='Duty')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty', to='resume.job', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Job Duties',
                'verbose_name_plural': 'Job Duties',
                'ordering': ['company'],
            },
        ),
    ]
