# Generated by Django 3.1.5 on 2021-01-22 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['certification'], 'verbose_name': 'Certifications', 'verbose_name_plural': 'Certifications'},
        ),
        migrations.AlterModelOptions(
            name='computerskill',
            options={'ordering': ['skill'], 'verbose_name': 'Computer Skills', 'verbose_name_plural': 'Computer Skills'},
        ),
        migrations.AlterModelOptions(
            name='generalinfo',
            options={'verbose_name': 'General Information', 'verbose_name_plural': 'General Information'},
        ),
        migrations.AlterModelOptions(
            name='interests',
            options={'ordering': ['interest'], 'verbose_name': 'Interests', 'verbose_name_plural': 'Interests'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['company'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobduty',
            options={'ordering': ['company'], 'verbose_name': 'Job Duties', 'verbose_name_plural': 'Job Duties'},
        ),
        migrations.AlterModelOptions(
            name='personalskill',
            options={'ordering': ['skill'], 'verbose_name': 'Personal Skills', 'verbose_name_plural': 'Personal Skills'},
        ),
    ]
