# Generated by Django 3.1.5 on 2021-01-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210122_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.CharField(max_length=255, verbose_name='Start Date'),
        ),
    ]
