# Generated by Django 3.1.5 on 2021-01-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210122_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobduty',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty', to='resume.job', verbose_name='Company'),
        ),
    ]
