# Generated by Django 3.1.5 on 2021-01-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210124_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='attending',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certification',
            field=models.CharField(max_length=255, verbose_name='Certification'),
        ),
        migrations.AlterField(
            model_name='computerskill',
            name='skill',
            field=models.CharField(max_length=255, verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='interests',
            name='interest',
            field=models.CharField(max_length=255, verbose_name='Interest'),
        ),
        migrations.AlterField(
            model_name='personalskill',
            name='skill',
            field=models.CharField(max_length=255, verbose_name='Skill'),
        ),
    ]
