# Generated by Django 3.1.5 on 2021-01-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210124_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='attending',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Currently Employed Here'),
        ),
    ]
