# Generated by Django 3.1.5 on 2021-01-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20210124_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['start_date'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='attending',
            new_name='currently_employed',
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(max_length=255, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(max_length=255, verbose_name='Start Date'),
        ),
    ]
