# Generated by Django 3.1.5 on 2021-01-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20210124_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='End Date'),
        ),
    ]
