# Generated by Django 3.1.5 on 2021-01-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20210124_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255, verbose_name='School Name')),
                ('degree', models.CharField(max_length=255, verbose_name='Degree Title')),
                ('gpa', models.CharField(max_length=255, verbose_name='GPA')),
                ('city_state', models.CharField(max_length=255, verbose_name='Location')),
                ('start_date', models.DateField(max_length=255, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, max_length=255, null=True, verbose_name='End Date')),
                ('currently_attending', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Currently Attending Here')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-currently_attending'],
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-currently_employed'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
