# Generated by Django 3.1.5 on 2021-01-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20210124_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-currently_enrolled'], 'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.RemoveField(
            model_name='education',
            name='currently_attending',
        ),
        migrations.AddField(
            model_name='education',
            name='currently_enrolled',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Currently Enrolled Here'),
        ),
    ]
